from pylab import *
from scipy.io import loadmat
import cPickle

Experiment_1=loadmat('1_375_0.33_h2o_20bar_max/processed_final.mat',squeeze_me=True)
Experiment_2=loadmat('2_375_0.33_h2o_86bar_max/processed_final.mat',squeeze_me=True)
Experiment_3=loadmat('3_375_0.33_h2o_6bars/processed_final.mat',squeeze_me=True)
Experiment_4=loadmat('4_375_0.33_h2o_13.5bars/processed_final.mat',squeeze_me=True)
Experiment_5=loadmat('5_375_0.33_h2o_he_13.5bars_hygrometer/processed_final.mat',squeeze_me=True)
Experiment_6=loadmat('6_375_0.33_h2o_h2_only/processed_final.mat',squeeze_me=True)
Experiment_7=loadmat('7_450_1_2_bar_h2o_h2he_premix/processed_final.mat',squeeze_me=True)
Experiment_8=loadmat('8_450_1bar_h2o_he_13bars/processed_final.mat',squeeze_me=True)
Experiment_9=loadmat('9_525_3bar_h2o_h2he_premix/processed_final.mat',squeeze_me=True)
Experiment_10=loadmat('10_525_1_8_bar_h2o_he_13bars/processed_final.mat',squeeze_me=True)
Experiment_11=loadmat('11_500_2bar_h2o_pure_h2/processed_final.mat',squeeze_me=True)
Experiment_12=loadmat('12_500_1bar_13.5_he/processed_final.mat',squeeze_me=True)
Experiment_13=loadmat('13_500_2bar_6bar_he/processed_final.mat',squeeze_me=True)
Experiment_14=loadmat('14_450_1bar_h2o_h2_only/processed_final.mat',squeeze_me=True)
Experiment_15=loadmat('15_450_2bar_6bars_he/processed_final.mat',squeeze_me=True)
Experiment_16=loadmat('16_450_1bar_13bars_he/processed_final.mat',squeeze_me=True)
Experiment_17=loadmat('17_333_0.1bar_13bar_he/processed_final.mat',squeeze_me=True)
Experiment_18=loadmat('18_375_0.5bar_13bar_he/processed_final.mat',squeeze_me=True)
Experiment_19=loadmat('19_333_0.05bar_13bar_he/processed_final.mat',squeeze_me=True)
Experiment_20=loadmat('20_500K_2bH2O_14bHe/processed_final.mat',squeeze_me=True)
Experiment_21=loadmat('21_500K_1.5bH2O_6bHe/processed_final.mat',squeeze_me=True)


file_handle=open('all_data.pkl','w')
cPickle.dump(Experiment_1,file_handle)
cPickle.dump(Experiment_2,file_handle)
cPickle.dump(Experiment_3,file_handle)
cPickle.dump(Experiment_4,file_handle)
cPickle.dump(Experiment_5,file_handle)
cPickle.dump(Experiment_6,file_handle)
cPickle.dump(Experiment_7,file_handle)
cPickle.dump(Experiment_8,file_handle)
cPickle.dump(Experiment_9,file_handle)
cPickle.dump(Experiment_10,file_handle)
cPickle.dump(Experiment_11,file_handle)
cPickle.dump(Experiment_12,file_handle)
cPickle.dump(Experiment_13,file_handle)
cPickle.dump(Experiment_14,file_handle)
cPickle.dump(Experiment_15,file_handle)
cPickle.dump(Experiment_16,file_handle)
cPickle.dump(Experiment_17,file_handle)
cPickle.dump(Experiment_18,file_handle)
cPickle.dump(Experiment_19,file_handle)
cPickle.dump(Experiment_20,file_handle)
cPickle.dump(Experiment_21,file_handle)
file_handle.close()
