from pylab import *
from scipy.io import loadmat
import cPickle

Experiment_1=loadmat('1_375_0.33_h2o_20bar_max/processed_final.mat')
Experiment_2=loadmat('2_375_0.33_h2o_86bar_max/processed_final.mat')
Experiment_3=loadmat('3_375_0.33_h2o_6bars/processed_final.mat')
Experiment_4=loadmat('4_375_0.33_h2o_13.5bars/processed_final.mat')
Experiment_5=loadmat('5_375_0.33_h2o_he_13.5bars_hygrometer/processed_final.mat')
Experiment_6=loadmat('6_375_0.33_h2o_h2_only/processed_final.mat')
Experiment_7=loadmat('7_450_1_2_bar_h2o_h2he_premix/processed_final.mat')
Experiment_8=loadmat('8_450_1bar_h2o_he_13bars/processed_final.mat')
#Experiment_9=loadmat()
#EXperiment_10=loadmat()

#file_handle=open('all_data.pkl','r')
#Experiment_1=cPickle.load(file_handle)
#Experiment_2=cPickle.load(file_handle)
#Experiment_3=cPickle.load(file_handle)
#Experiment_4=cPickle.load(file_handle)
#Experiment_5=cPickle.load(file_handle)
#Experiment_6=cPickle.load(file_handle)
#Experiment_7=cPickle.load(file_handle)
#Experiment_8=cPickle.load(file_handle)
#file_handle.close()
file_handle=open('all_data.pkl','w')
cPickle.dump(Experiment_1,file_handle)
cPickle.dump(Experiment_2,file_handle)
cPickle.dump(Experiment_3,file_handle)
cPickle.dump(Experiment_4,file_handle)
cPickle.dump(Experiment_5,file_handle)
cPickle.dump(Experiment_6,file_handle)
cPickle.dump(Experiment_7,file_handle)
cPickle.dump(Experiment_8,file_handle)
file_handle.close()
